[versions]
coroutines = "1.8.1" # https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-serialization = "1.7.1" # https://github.com/Kotlin/kotlinx.serialization/releases
legacy-json = "20240303" # https://github.com/stleary/JSON-java/releases
legacy-moshi = "1.15.1" # https://github.com/square/moshi/blob/master/CHANGELOG.md
legacy-rxjava = "3.1.8" # https://github.com/ReactiveX/RxJava/releases
mockito = "5.3.1" # https://github.com/mockito/mockito-kotlin/releases

[libraries]
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
legacy-json = { group = "org.json", name = "json", version.ref = "legacy-json" }
legacy-moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "legacy-moshi" }
legacy-rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "legacy-rxjava" }
mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" } # https://github.com/JLLeitschuh/ktlint-gradle/releases
